### ISSUE TITLE
Does not appear to be inside a project error.

### ISSUE THREAD

**Issue by atmacafurkan** [nstrayer/datadrivencv#1]
I dont know if I am doing this wrong but I get the following error even when using the example code: 

`Error: Path '/home/user/Downloads/cv/' does not appear to be inside a project or package.`

**Comment by technOslerphile** [comment]
Hi, can you please tell how did you solve this if indeed you found a solution?

**Comment by nstrayer** [comment]
This should be solved by using the RStudio project workflow. Apparently the `usethis` function I used to build the cv template depends on being in a project format.

**Comment by nstrayer** [comment]
Re-opening because I never explicitly mention this and I shouldn't have a dependency on the IDE used.

**Comment by BraymNoodles** [comment]
I solve it checking out this page "https://r4ds.had.co.nz/workflow-projects.html" and creating a project inside R studio. Hope it will help you.

**Comment by nstrayer** [comment]
#22 update fixes this by using a custom template building function instead of the one provided by `usethis`. This new one relies on working directories instead of the project structure.
