### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by ejosymart** [nstrayer/datadrivencv#10]
I am having this error:

"ERROR: dependency 'icon' is not available for package 'datadrivencv'"

Is icon an R package?

**Comment by nstrayer** [comment]
This is related to https://github.com/nstrayer/datadrivencv/issues/9.

**Comment by nstrayer** [comment]
Like #9, I believe that this should be fixed by #11. I'll re-open if it isn't. Thanks so much for the report!
