### ISSUE TITLE
new entries not showing up

### ISSUE THREAD

**Issue by lepardov2020** [nstrayer/datadrivencv#18]
I added a few entries like courses, affiliations or awards, and deleted some of the original entries like by_me_press or about_me_press. However, the new entries are not shown in the cv and your default fields or entries are still in the cv but with a long error message. e.g. for section "SELECTED PRESS (ABOUT), this error is printed in the CV "## Warning in stri_extract_all_regex(string, pattern, simplify = simplify, : argument is not an atomic 
## vector; coercing "
 is it not possible to add or delete entries?
thanks

**Comment by nstrayer** [comment]
Interesting... Did you leave the printing statements for the removed sections in the rmd?
E.g. 
````
...
Selected Press (About)  {data-icon=newspaper}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('about_me_press')
```
...
````
? 
If not, can you try taking additions away until it works to find the offending row and then post that row? There's a chance that my regular expression parsing is getting broken on an edge case I didn't consider.

**Comment by lepardov2020** [comment]
working now, thanks! I was able to remove and add new sections, thanks a lot for this cool package.
