### ISSUE TITLE
online version is the actual path in my PC

### ISSUE THREAD

**Issue by lepardov2020** [nstrayer/datadrivencv#28]
When setting the   html_location, I imagine one should have an actual online version of the cv, right? or should one create this "page" before in order to have the online version? It seems I still have the actual path in my computer for the HTML output  (i.e. file:///C:/Users/admin/Hoja%2....html not a "...me/cv"

thanks!

ps. I just created a note at the end of my resume (small cv) where I want to link the long cv, but had to use my google drive file (pdf of my cv)

**Comment by nstrayer** [comment]
Yeah. You'll want to use the hosted version for the HTML. The easiest way is by using Github pages with a repo you have for storing your CV. So something like `https://lepardov2020.github.io/cv/cv.html`.  That way whenever you update it your hosted version automatically updates as well.
