### ISSUE TITLE
knit pdf error

### ISSUE THREAD

**Issue by lepardov2020** [nstrayer/datadrivencv#29]
I can create my html version but when I try to knit it for the pdf I get this error:
Quitting from lines 201-202 (cv_1.Rmd) 
 Error: `nm` must be `NULL` or a character vector the same length as `x` 

Any thoughts? thanks

**Comment by kara-swartz** [comment]
I had the same error when I used square brackets [] in googlesheets. In markdown it's a link

**Comment by lepardov2020** [comment]
Thanks, just double checked and it seems that I am using the syntax correctly. E.g. if I want to read a hyperlink I write [doi](https://doi.org/10.1016/J.BIOCON.2018.08.026). I get in the cv only the [] part. In other sections, I use the whole address starting from http: since I noticed if I don´t start from there it won´t be read as a link on the online version. So, not sure, but yes if I get rid of all the links it runs, but I would prefer being able to include them. Cheers. Let´s see if there is another experience. thanks

**Comment by nstrayer** [comment]
Hi! Sorry for the slow response. 

Quick fix:
Go into `cv_printing_functions.r` and replace the lines that start with `link_titles <-` and `link_destinations<-` with
```
    link_titles <- stringr::str_extract_all(text, '(?<=\\[).+?(?=\\]\\()')[[1]]
    link_destinations <- stringr::str_extract_all(text, '(?<=\\]\\().+?(?=\\))')[[1]]
```

Slower fix: I have [a branch that fixes this](https://github.com/nstrayer/datadrivencv/tree/allow_square_brackets) that will be merged to master soon so you can update to that and then run:

```
datadrivencv::use_datadriven_cv(
    which_files = c( "cv_printing_functions.r"),
    open_files = FALSE
)
```
To get the new version of the cv printing functions script. 

What was going on was my regular expressions for grabbing markdown links assumed that any text that was surrounded in square brackets was the title for a markdown link. Now that square bracketed text must be followed by a round bracket for it to be detected.

**Comment by nstrayer** [comment]
I tested by using the following text for a description: 

`Thesis: An [agent] based (model) of Diel Vertical Migration patterns of Mysis diluviana`

The result looks like this: 

![image](https://user-images.githubusercontent.com/6764693/85958553-eeeea080-b95b-11ea-90bc-9ca243dd51e9.png)

**Comment by lepardov2020** [comment]
Thank you Nick, it seems to be working now!
all the best!
