### ISSUE TITLE
Dependency issue (icon)

### ISSUE THREAD

**Issue by Rudolph-afk** [nstrayer/datadrivencv#71]
I'm trying to install the package on R 4.1.1 (Windows 10) and the installation fails because it can't find the package 'icon'. I subsequently tried installing it on R 4.1.1 via Ubuntu (WSL2) and still on the same issue. I then downgraded to R 3.6.3 on Ubuntu (WSL) and still the same dependency issue. I then checked the DEPENDENCY file on the repo and tried to manually find and install the package but I can't find the package.
![2021-09-13](https://user-images.githubusercontent.com/60734499/133138771-43492b99-f69a-4fd0-bd51-4f8a3317937c.png)

**Comment by hughcross** [comment]
I had the same problem on Mac OSX

**Comment by hughcross** [comment]
Hello Rudolph, and anyone else having this problem. 

There are a few solutions to this I found. [**#57**](https://github.com/nstrayer/datadrivencv/issues/57) worked for me

specifically:

```
remotes::install_github('mitchelloharawild/icons@v0.1.0')
```

I hope this helps

**Comment by Rudolph-afk** [comment]
It worked. Thanks!
